security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        main:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            provider: main
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard
                always_use_default_target_path: true
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }

