security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        main:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            provider: main
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard
                always_use_default_target_path: true
            logout:
                path: logout
                target: login

    access_control:
            - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, role: IS_AUTHENTICATED_FULLY }