App\DTO\ProductDTO:
    properties:

        model:
            - Length:
                min: 3
                max: 100
                minMessage: 3 caractères minimum
                maxMessage: 100 caractères maximum
                groups: [product]

        price:
            - Type:
                type: float
                message: Veuillez un prix comprenant au moins deux décimales
                groups: [product]


        family:
            - NotBlank: { groups: [product] }


        category:
            - NotBlank: { groups: [product] }

        type:
            - NotBlank: { groups: [product] }

        make:
            - NotBlank: { groups: [product] }

        designation:
            - NotBlank: { groups: [product] }