App\DTO\UserDTO:
    properties:

        name:
            - Length:
                min: 3
                max: 20
                minMessage: 3 caractères minimum
                maxMessage: 20 caractères maximum
                groups: [user]

        surname:
            - Length:
                min: 3
                max: 50
                minMessage: 3 caractères minimum
                maxMessage: 50 caractères maximum
                groups: [user]

        email:
            - NotBlank: { groups: [user] }


        role:
            - NotBlank: { groups: [user] }
