App\DTO\WarehouseDTO:
    properties:
        name:
            - Length:
                min: 3
                max: 150
                minMessage: 3 caractères minimum
                maxMessage: 150 caractères maximum
                groups: [warehouse]

        address:
           - Length:
               min: 5
               max: 150
               minMessage: 3 caractères minimum
               maxMessage: 150 caractères maximum
               groups: [warehouse]